# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/main_menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainMenu(object):
    def setupUi(self, MainMenu):
        MainMenu.setObjectName("MainMenu")
        MainMenu.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainMenu)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setStyleSheet("font-size: 28px; font-weight: bold;")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.btn_start = QtWidgets.QPushButton(self.centralwidget)
        self.btn_start.setMinimumSize(QtCore.QSize(0, 50))
        self.btn_start.setObjectName("btn_start")
        self.verticalLayout.addWidget(self.btn_start)
        self.btn_history = QtWidgets.QPushButton(self.centralwidget)
        self.btn_history.setMinimumSize(QtCore.QSize(0, 50))
        self.btn_history.setObjectName("btn_history")
        self.verticalLayout.addWidget(self.btn_history)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout.setStretch(2, 1)
        MainMenu.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainMenu)

    def retranslateUi(self, MainMenu):
        _translate = QtCore.QCoreApplication.translate
        MainMenu.setWindowTitle(_translate("MainMenu", "Главное меню"))
        self.label.setText(_translate("MainMenu", "Главное меню"))
        self.btn_start.setText(_translate("MainMenu", "🚀 Начать бонитировку"))
        self.btn_history.setText(_translate("MainMenu", "📄 История"))
