# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/owner_select.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OwnerSelect(object):
    def setupUi(self, OwnerSelect):
        OwnerSelect.setObjectName("OwnerSelect")
        OwnerSelect.resize(1000, 700)
        self.centralwidget = QtWidgets.QWidget(OwnerSelect)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.input_search = QtWidgets.QLineEdit(self.centralwidget)
        self.input_search.setObjectName("input_search")
        self.verticalLayout.addWidget(self.input_search)
        self.btn_search = QtWidgets.QPushButton(self.centralwidget)
        self.btn_search.setObjectName("btn_search")
        self.verticalLayout.addWidget(self.btn_search)
        self.list_owners = QtWidgets.QListWidget(self.centralwidget)
        self.list_owners.setObjectName("list_owners")
        self.verticalLayout.addWidget(self.list_owners)
        self.btn_add_owner = QtWidgets.QPushButton(self.centralwidget)
        self.btn_add_owner.setObjectName("btn_add_owner")
        self.verticalLayout.addWidget(self.btn_add_owner)
        self.btn_continue = QtWidgets.QPushButton(self.centralwidget)
        self.btn_continue.setObjectName("btn_continue")
        self.verticalLayout.addWidget(self.btn_continue)
        OwnerSelect.setCentralWidget(self.centralwidget)

        self.retranslateUi(OwnerSelect)

    def retranslateUi(self, OwnerSelect):
        _translate = QtCore.QCoreApplication.translate
        OwnerSelect.setWindowTitle(_translate("OwnerSelect", "Выбор хозяйства"))
        self.input_search.setPlaceholderText(_translate("OwnerSelect", "Введите имя или телефон владельца"))
        self.btn_search.setText(_translate("OwnerSelect", "🔍 Найти"))
        self.btn_add_owner.setText(_translate("OwnerSelect", "➕ Добавить нового"))
        self.btn_continue.setText(_translate("OwnerSelect", "✅ Продолжить"))
